[package]
name = "my-blog"
version = "0.1.0"
authors = ["LiYongchao"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
serde_json = "1.0"
comrak = "0.4"
handlebars = "1.1.0"
structopt = "0.2.15"
